import Foundation

/// Daily horoscope cache over the existing JSONStore. One entry per
/// `horoscope:{localDate}:{zodiacSign}:{locale}`; entries from earlier
/// dates are pruned on save so the file stays tiny. Reopening the
/// screen on the same day always returns the cached result — content is
/// never regenerated by card expansion or re-entry.
@MainActor
final class HoroscopeCache: ObservableObject {
    private var entries: [String: DailyHoroscope]
    private let store: JSONStore
    private nonisolated static let fileName = "horoscope_cache"

    nonisolated init(store: JSONStore = JSONStore()) {
        self.store = store
        entries = store.load([String: DailyHoroscope].self, from: Self.fileName) ?? [:]
    }

    static func key(dateKey: String, sign: ZodiacSign, lang: AppLanguage) -> String {
        "horoscope:\(dateKey):\(sign.canonicalID):\(lang.rawValue)"
    }

    func cached(dateKey: String, sign: ZodiacSign, lang: AppLanguage) -> DailyHoroscope? {
        entries[Self.key(dateKey: dateKey, sign: sign, lang: lang)]
    }

    func save(_ horoscope: DailyHoroscope, sign: ZodiacSign, lang: AppLanguage) {
        // Prune other dates so the cache holds only the current day.
        entries = entries.filter { $0.value.dateKey == horoscope.dateKey }
        entries[Self.key(dateKey: horoscope.dateKey, sign: sign, lang: lang)] = horoscope
        store.save(entries, as: Self.fileName)
    }
}
